### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by she9903** [kyoustat/Rdimtools#1]
Hi. 

I have tried to install the Rdimtools package to my R(version 3.4.3) but there is an error of
" (Error: package or namespace load failed for ‘Rdimtools’:
 object ‘admm.rpca’ is not exported by 'namespace:ADMM'"

It seems okay 2 weeks ago. But when I try to run the package again this week, it does not install. 

I have tried to use " devtools::install_github("kisungyou/Rdimtools")", but also not working.

Appreciate if you can advise me on this matter.

Thanks

**Comment by kisungyou** [comment]
Hi @she9903 ,

I feel sorry to see any issues this late. Based on my opinion, it seems that ADMM package was not properly updated in the meantime. Now it should have no problem since two packages are all properly updated on CRAN. Please update your packages and let me know if you have any further problems.

Regards
Kisung
